name: Build EDH Tlty APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Construire APK avec Docker Kivy
        run: |
          docker pull ghcr.io/kivy/buildozer:latest
          docker run --rm \
            -v "$PWD":/home/user/hostcwd \
            ghcr.io/kivy/buildozer:latest \
            android debug

      - name: Télécharger APK
        uses: actions/upload-artifact@v4
        with:
          name: EDH-Tlty-APK
          path: bin/*.apk
