name: Build EDH Tlty APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install "cython==0.29.37" "buildozer==1.6.0"

      - name: Accepter les licences Android
        run: |
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses || true

      - name: Installer Build Tools
        run: |
          "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" \
            "build-tools;35.0.0" \
            "platform-tools" \
            "platforms;android-35"

      - name: Construire APK
        run: |
          python -m pip install "pip==24.0"
          buildozer android debug

      - name: Télécharger APK
        uses: actions/upload-artifact@v4
        with:
          name: EDH-Tlty-APK
          path: bin/*.apk
