name: Build EDH Tlty APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Construire APK
        uses: docker://ghcr.io/kivy/buildozer:latest
        with:
          entrypoint: /bin/bash
          args: -c "buildozer android debug"

      - name: Télécharger APK
        uses: actions/upload-artifact@v4
        with:
          name: EDH-Tlty-APK
          path: bin/*.apk
